# Generated by Django 4.2.30 on 2026-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_name_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createPassword',
            new_name='PasswordResetOTP',
        ),
    ]
