# Generated by Django 6.0.4 on 2026-05-04 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_createpassword_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='access_token',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 10, 46, 49, 827824, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='token_hash',
            field=models.CharField(default=datetime.datetime(2026, 5, 4, 10, 47, 4, 435699, tzinfo=datetime.timezone.utc), max_length=64),
            preserve_default=False,
        ),
    ]
