# Generated by Django 6.0.4 on 2026-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
