# Generated by Django 6.0.4 on 2026-05-09 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_perfume_price_perfume_stock_delete_perfumevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
