# Generated by Django 6.0.4 on 2026-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_perfume_description_alter_perfume_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
